### ISSUE TITLE
bash temporary files causes watching the server to crash

### ISSUE THREAD

**Issue by tonyaedmonds** [pattern-lab/edition-php-mustache-webdesignday#1]
When using bash shell, it creates temporary files with the suffix '~' or surrounded by '#.' 

If I edit a file at the command-line (e.g. using emacs) these temp files are created and produces an error similar to this and crashes the `--watch` command from listening to changes:

Example 1
`atoms-colors~ wasn't found for loading. the given path: /Users/tonyaedmonds/projects/my-project/source/_patterns/00-atoms/01-global/00-colors~.mustache`

or this (Example 2)
`molecules-#02-my-block# wasn't found for loading. the given path: /Users/tonyaedmonds/projects/my-project/source/_patterns/01-molecules/01-blocks/#02-my-block#.mustache`

In the first example, the shell created the file `00-colors.mustache~`

**Comment by dmolsen** [comment]
@tonyaedmonds -

I'm not tracking this as a bug for Pattern Lab Core. Should be fixed this week. Thanks again for the report. Have a good day.

**Comment by dmolsen** [comment]
@tonyaedmonds -

This has been mainly addressed with the release of `v2.5.0` of Pattern Lab Core. The old code wasn't an explicit check. It is now. This way `.mustache~` or `.mustache.swp` won't cause issues. I'll have to look at options for the other type of example.

To get the latest version of core type the following in the root of your project:

```
composer update pattern-lab/core
```
